#!/usr/bin/perl

use warnings;
use strict;

my $directory = "$ENV{'HOME'}/test/";
my %preserve;
my @list = qw(
	DELETE
);

$preserve{$_}++ for @list;

opendir DIR, $directory or die "Directory open failed\n";
while (my $filename = readdir(DIR)) {
	next if $filename =~ /^\.+$/;
	unless ($preserve{"$filename"}) {
		(unlink "$filename" or system("rm", "-rf", "$filename") == 0)
				or die "$filename: Unlink failed\n";
		print "Deleted: $filename\n"
	}
}
closedir DIR or die "Directory close failed\n";
