#!/usr/bin/perl

use warnings;
use strict;

my $directory = "$ENV{'HOME'}/.dotfiles/test";
my %preserve;
my @list;

open my $fh, "<list" or die "open failed\n";
while (<$fh>) { chomp; push @list, $_ }
close $fh or die "close failed\n";
$preserve{$_}++ for @list;

(system("cp", "$_", "$directory") == 0) or die "$_: move failed\n" for @list;

system("diff", "$_", "$directory/$_") for @list;

chdir $directory;
opendir DIR, $directory or die "Directory open failed\n";
while (my $filename = readdir(DIR)) {
	next if $filename =~ /^\.{1,2}$/;
	unless ($preserve{"$filename"}) {
		system("rm", "-rf", "$filename") == 0
				or die "$filename: Unlink failed\n";
		print "Deleted: $filename\n"
	}
}
