#!/usr/bin/perl

use warnings;
use strict;

my $src_dir = "$ENV{'HOME'}/test";
my $dst_dir = "$ENV{'HOME'}/.dotfiles/test";
my %preserve;
my @list;

open my $fh, "<$src_dir/list" or die "open failed\n";
while (<$fh>) { chomp; push @list, $_ }
close $fh or die "close failed\n";
$preserve{$_}++ for @list;

(system("cp", "-R", "$_", "$dst_dir") == 0) or die "$_: move failed\n" for @list;

system("diff", "$src_dir/$_", "$dst_dir/$_") for @list;

chdir $dst_dir;
opendir DIR, $dst_dir or die "Directory open failed\n";
while (my $filename = readdir(DIR)) {
	next if $filename =~ /^\.{1,2}$/;
	unless ($preserve{"$filename"}) {
		system("rm", "-rf", "$filename") == 0
				or die "$filename: Unlink failed\n";
		print "Deleted: $filename\n"
	}
}
