##############Initial Setting#####################
#   [TPM]
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

#256 color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

#Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

#No escape delay
set -sg escape-time 0

#Vi Motion
setw -g mode-keys vi
#set status-keys vi         #nice option but I can't quit command prompt


#Status Baaar
set -g status off
set -g status-position top
set -g status-interval 42069      #This Makes Tmux Blazingly Faaaast(Not Really)

#tmux-yank
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
set -g @yank_selection 'clipboard' # 'primary' or 'secondary' or 'clipboard'

#display pane time
set -g display-panes-time 5000







#################Remap############################

#C-b to C-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


#Kill window without asking
bind x kill-window


#swap window
bind -r < swap-window -d -t -1
bind -r > swap-window -d -t +1

#reload
bind r source-file ~/.tmux.conf

#split
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"


#kwikbreak
bind b command-prompt -p "break>" { neww '~/bin/kwikbreak_asdf %%' }

#perldoc
bind p command-prompt -p "perldoc>" { neww '~/util/perldoc %%%' }

#quicknote
bind n command-prompt -p "note>" { run 'printf "%%%" | ~/util/note' }

#manpage prompt
bind m command-prompt -p "man>" { neww '~/util/tmux-man %%' }

#C const
bind C command-prompt -p "const>" { neww '~/util/tmugs-const %%%'}

#hangul
bind h command-prompt -p "hangul>" { run 'echo "%%%" | ~/util/han -cs 1>/dev/null'}

#dec to hex
bind e command-prompt -p "dth>" { run '~/util/dectohex %%% | tee >(xsel -i -b)'}

#hex to dec
bind E command-prompt -p "htd>" { run '~/util/hextodec %%% | tee >(xsel -i -b)'}

#Fast Neofetch
bind N neww "neofetch | ~/util/slowcat -1.3; sleep 3"

#Fast date / cal
bind D neww "cal -3; date; sleep 60"




#Move Love Alt Native
bind -n M-h previous-window
bind -n M-l next-window

bind -n M-j select-pane -t :.+
bind -n M-k select-pane -t :.-

bind -n M-a resize-pane -Z
bind -n M-e set -g status
bind -n M-Tab last-window
bind -n M-n neww -n 'NOTE' 'cd ~/note/ ; nvim index.md'
bind -n M-m run-shell -b "~/util/tmugs-man|| exit 0; exec bash"
bind -n M-Enter run-shell -b "~/util/tmugs-cd || exit 0; exec bash"
bind -n M-Space run-shell -b "~/util/tmugs-vim || exit 0; exec bash"
bind -n M-Escape choose-tree -Zw
bind -n M-q run-shell -b "~/util/tmugs-alias || exit 0; exec bash"
bind -n "M-/" list-keys -N
bind -n "M-?" list-keys
bind -n "M-;" clock-mode
bind -n "M-'" copy-mode
bind -n "M-:" command-prompt

bind -n M-J resize-pane -D 4
bind -n M-K resize-pane -U 4
bind -n M-H resize-pane -L 4
bind -n M-L resize-pane -R 4


bind -n M-1 new -A -s 1
bind -n M-2 new -A -s 2
bind -n M-3 new -A -s 3
bind -n M-4 new -A -s 4
bind -n M-5 new -A -s 5

bind -n M-o switchc -n
bind -n M-i switchc -p

bind -n M-u swapp -D
bind -n M-p swapp -U















#################Status Bar#######################
set -g status-bg black
set -g status-fg green
set -g status-left ''
set -g status-left-length 0
set -g status-right-length 0
set -g status-right ''
set -g window-status-format "*#{window_name}*"
set -g window-status-current-format "#[fg=black]#[bg=green] #{window_name} "
set -g message-style 'bg=black, fg=green bold'
