#!/bin/bash

mv ~/.bashrc ~/.bashrc_bak
mv ~/.bash_profile ~/.bash_profile_bak
stow .

mkdir -p ~/src
cd ~/src
for i in {dmenu,dwm,st,slock}
do
	git clone git://git.suckless.org/$i || exit 99
	ln -sn ~/.dotfiles/src/$i/config.h ~/src/$i/config.h
	ln -sn ~/.dotfiles/src/$i/*.diff ~/src/$i
done
cd -

ln -sn /tmp/test_${USER} ~/test
ln -sn ~/personal/projects/ ~/projects
