--I heard that I need to edit g:user_emmet_leader_key in ~/.local/share/nvim/lazy/emmet-vim/plugin/emmet.vim but It's too late to edit keymaps so I just remapped directly
vim.g.user_emmet_leader_key='<C-e>'
vim.g.user_emmet_expandabbr_key = '<C-e>,'
vim.g.user_emmet_expandword_key = '<C-e>;'
vim.g.user_emmet_update_tag = '<C-e>u'
vim.g.user_emmet_balancetaginward_key = '<C-e>d'
vim.g.user_emmet_balancetagoutward_key = '<C-e>D'
vim.g.user_emmet_next_key = '<C-e>n'
vim.g.user_emmet_prev_key = '<C-e>N'
vim.g.user_emmet_imagesize_key = '<C-e>i'
vim.g.user_emmet_togglecomment_key = '<C-e>/'
vim.g.user_emmet_splitjointag_key = '<C-e>j'
vim.g.user_emmet_removetag_key = '<C-e>k'
vim.g.user_emmet_anchorizeurl_key = '<C-e>a'
vim.g.user_emmet_anchorizesummary_key = '<C-e>A'
vim.g.user_emmet_mergelines_key = '<C-e>m'
vim.g.user_emmet_codepretty_key = '<C-e>c'
