--require'nvim-treesitter.configs'.setup {
--  incremental_selection = {
--    enable = true,
--    keymaps = {
--      init_selection = "<CR>",
--      node_incremental = "<CR>",
--      scope_incremental = "<S-CR>",
--      node_decremental = "<BS>",
--    },
--  },
--}
