#!/bin/perl
use utf8;
use strict;
use warnings;
use diagnostics;
use feature qw/
    say
/;

my $pattern;
my $var = 'i';

do{
    print "Enter the pattern: ";
    chomp($pattern = <STDIN>);
    eval { "" =~ /$pattern/ };
    warn "INVALID PATTERN $@" if $@;
} while $@;
print "Enter the string: ";
while (<>) {
    chomp;
    say "Matched! [$`<$&>$']" if (m/${pattern}/);
    print "Enter the string: ";
}
