#!/bin/sh

file=$(ls -R /usr/include/*.h | cut -d/ -f 4- |
fzf-tmux -p 80% --bind change:first --tiebreak=chunk --border-label "TMUGS-CH");
[ -z $file ] && exit 0
tmux neww -c "/usr/include" "nvim $file"
