#!/usr/bin/sh

url=$(fzf --with-nth=1,2 -n1 -d'\|' <~/util/ieee/idx_list | cut -d '|' -f3)
[ -z "$url" ] && exit 0
[ "$url" = "TOPIC" ] && exec ~/util/ieee/top 
firefox --new-tab https://pubs.opengroup.org/onlinepubs/9799919799/$url
