#!/usr/bin/sh

function tmux_echo {
	tmux run -t 1: "echo $1"
}

msg_low="Battery Low. Charge the battery"
msg_high="Battery is charged enough."

while true
do
	capacity=$(cat /sys/class/power_supply/BAT0/capacity)
	status=$(cat /sys/class/power_supply/BAT0/status)

	if [ ${capacity} -le 25 ] && [ ${status} != "Charging" ] then
		aplay -q ~/wav/low.wav
		tmux_echo "${capacity}: ${msg_low}"
	fi
	if [ ${capacity} -ge 75 ] && [ ${status} != "Discharging" ] then
		aplay -q ~/wav/charged.wav
		tmux_echo "${capacity}: ${msg_high}"
	fi

	sleep 90
done
