#!/bin/sh

location=$(find -L ~ -mindepth 1 -maxdepth 3 -type d |
    ~/util/dirsed | sed '1itest\n\/' |fzf --margin 13% --border-label="somewhere over teh lainbow")

[ "$location" = "/" ] && cd $(find / -mindepth 1 -maxdepth 3 -type d 2>/dev/null|
    fzf --margin 13% --bind change:first --border-label "TMUGS-CD-ROOT") && location=""

[ -z "$location" ] || cd ~/"$location"
