#!/bin/sh

loc=$(find -L ~ -mindepth 1 -maxdepth 3 -type d | ~/util/dirsed |
	sed '1itest\n\/' | fzf --border-label="somewhere over teh lainbow")

[ "$loc" = "/" ] && cd $(find / -mindepth 1 -maxdepth 3 -type d 2>/dev/null |
	fzf --bind change:first --border-label "TMUGS-CD-ROOT") && loc=""

[ -z "$loc" ] || cd ~/"$loc"
