#!/bin/sh

#url=$(grep -v '^#' ~/personal/firefox_list | column -t |\
#    fzf-tmux -p 80% -n 1,2 --with-nth=1,2,3 \
#    --tiebreak=begin --bind change:first --border-label "TMUGS-FIREFOX" |\
#    perl -ae '$F[3] = $F[3] =~ m#^https://www.youtube.com# ? $F[3]."&t=".$F[2] : $F[3].$F[2] if $F[2] ne "."; print $F[3]')

url=$(perl -e 'my @list; while(<>){chomp; push @list, $_}
	@list = sort {($a1)=($a=~/(\d+)$/); ($b1)=($b=~/(\d+)$/); $sum=$a1+$b1;
		unless($sum){return 0} if($sum==$a1){-1} elsif($sum==$b1){1} else {$a1<=>$b1}} @list;
	print "$_\n" for @list' < ~/personal/firefox_asdf | column -t -s',' |\
    fzf-tmux -p 80% -n 1,2 --with-nth=1,2,4 \
	--tiebreak=begin --bind change:first --border-label "TMUGS-FIREFOX")
[ -z "$url" ] && exit 0

export url
perl -e '$url=$ENV{url}; $url = splice @{[split " ", $url]}, 2, 1;
	open $fh, "<", "$ENV{HOME}/personal/firefox_asdf" or die "open failed\n";
	my @list;
	while(<$fh>){chomp; /(.*,)([^,]+)$/; $aaa=$1; $num=$2;
		if(/\Q$url\E/){$num=1} else{$num = $num ? $num+1 : 0} push @list, "$aaa$num"}
	close $fh or die "close failed\n";
	open $fh, ">", "$ENV{HOME}/personal/firefox_asdf" or die "open failed\n";
	print $fh "$_\n" for @list;
	close $fh or die "close failed\n"'
url=$(echo "$url" | perl -ae '$F[2] = $F[2] =~ m#^https://www.youtube.com# ? $F[2]."&t=".$F[3] : $F[2].$F[3] if $F[3] ne "."; print $F[2]')

firefox --new-tab $url
