#!/bin/perl
use utf8;
#use strict;
#use warnings;
#use Data::Dumper;
#use feature qw/
#    say
#/;
use Switch;

#Alphabet to Hangul
#Original code is from theyt.net
#Usage ./han "Alphabet String"


exit 69 unless @ARGV;
binmode(STDOUT, ":encoding(UTF-8)");


my @alp_key = split //, "rRseEfaqQtTdwWczxvgkoiOjpuPhynbml";
my @kor_key = split //, "ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎㅏㅐㅑㅒㅓㅔㅕㅖㅗㅛㅜㅠㅡㅣ";
my @cho_data = split //, "ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ";
my @jung_data = split //, "ㅏㅐㅑㅒㅓㅔㅕㅖㅗㅘㅙㅚㅛㅜㅝㅞㅟㅠㅡㅢㅣ";
my @jong_data = split //, "ㄱㄲㄳㄴㄵㄶㄷㄹㄺㄻㄼㄽㄾㄿㅀㅁㅂㅄㅅㅆㅇㅈㅊㅋㅌㅍㅎ";

my $ret;
my @ret;
my $src = join ' ', @ARGV;
my @src = split //, $src;

my $cho;
my $jung;
my $jong;



sub hangul{
    my @arr = @_;
    $_ //= -1 for (@arr);
    my $var = 0xac00 + 21*28*$arr[0] + 28*$arr[1] + $arr[2] + 1;
    push @ret, chr($var);
}

sub jung_index{
    my $ch_jung = $_[0];
    my $index_temp;
    for(my $i=0; $i<=$#jung_data; $i++){
        if($ch_jung eq $jung_data[$i]){
            $index_temp = $i;
            last;
        }
    }
    $index_temp;
}

sub jong_index{
    my $ch_jong = $_[0];
    my $index_temp;
    for(my $i=0; $i<=$#jong_data; $i++){
        if($ch_jong eq $jong_data[$i]){
            $index_temp = $i;
            last;
        }
    }
    $index_temp;
}

my %double_jaeum = (
    "0,9" => 2,
    "3,12" => 4,
    "3,18" => 5,
    "7,0" => 8,
    "7,6" => 9,
    "7,7" => 10,
    "7,9" => 11,
    "7,16" => 12,
    "7,17" => 13,
    "7,18" => 14,
    "16,9" => 17,
);

my %double_moeum = (
    "8,19" => 9,
    "8,20" => 10,
    "8,32" => 11,
    "13,23" => 14,
    "13,24" => 15,
    "13,32" => 16,
    "18,32" => 19,
);

sub jaeum{
    my ($ch, $index) = @_;
    if(!defined $jung){
        if(!defined $jong){
            if(!defined $cho){
                $cho = $index;
            } else {
                push @ret, $cho_data[$cho];
                $cho = $index;
            }
        }
    } else {
        if(!defined $jong){
            if(!defined $cho){
                push @ret, $jung_data[$jung];
                undef $jung;
                $cho = $index;
            } else {
                $jong = jong_index($ch);
            }
        } else {
            if(defined $cho){
                if( my $var = $double_jaeum{"$jong,$index"} ){
                    $jong = $var;
                    hangul($cho, $jung, $jong);
                    undef $jung;
                    undef $jong;
                    undef $cho;
                } else {
                    hangul($cho, $jung, $jong);
                    undef $jung;
                    undef $jong;
                    $cho = $index;
                }
            }
        }
    }
}

sub moeum{
    my ($ch, $index) = @_;

    if(!defined $cho){
        push @ret, $ch;
    } else {
        if(!defined $jong){
            if(!defined $jung){
                $jung = jung_index($ch);
            } else {
                if(my $var = $double_moeum{"$jung,$index"}){
                    my %rev = reverse %double_moeum;
                    $jung = $var;
                } else {
                    hangul($cho, $jung, $jong);
                    undef $cho;
                    $jung = $index_temp;
                }
            }
        } else {
            my $cho_temp;
            my $jong_temp;
            my %rev = reverse $double_jaeum;
            if(my $var = $rev{$jong}){
                $var =~ /(\d)+,(\d)+/;
                $jong = $1;
                $cho_temp = $2;
                hangul($cho, $jung, $jong);
                undef $jong;
            } else {
                $jong_temp = $jong;
                undef $jong;
                hangul($cho, $jung, $jong);
            }

            for(my $i=0; $i<=$#cho_data; $i++){
                if($jong_data[$jong_temp] eq $cho_data[$i]){
                    $jong_temp = $i;
                    last;
                }
            }

            if(defined $cho_temp){
                $cho = $cho_temp;
            } else {
                $cho = $jong_temp;
            }
            $jung = jung_index($ch);
        }
    }
}




for my $ch_src(@src){           #Start point
    my $index;

    for(my $i=0; $i<=$#alp_key; $i++){
        if ($ch_src eq $alp_key[$i]){
            $ch_src = $kor_key[$i];
            $index = $i;
            last;
        }
    }

    if(!defined $index){
        hangul($cho, $jung, $jong);
        undef $cho;
        undef $jung;
        undef $jong;
        push @ret, $ch_src;
        next;
    }

    if($index < 19){
        jaeum($ch_src, $index);
    } else {
        moeum($ch_src, $index);
    }
}



if(defined $cho){
    if(defined $jung){
        hangul($cho, $jung, $jong);
    } else {
        push @ret, $cho_data[$cho];
    }
} else {
    if(defined $jung){
        push @ret, $jung_data[$jung];
    } else {
        push @ret, $jong_data[$jong] if(defined $jong);
    }
}

$ret = join '', @ret;
print $ret;
