#!/bin/perl
use utf8;
#use strict;
#use warnings;
#use Data::Dumper;
#use feature qw/
#    say
#/;
use Switch;

#Alphabet to Hangul
#Original code is from theyt.net
#Usage ./han "Alphabet String"


exit 69 unless @ARGV;                       #Add schell later
binmode(STDOUT, ":encoding(UTF-8)");


#my @alp_key = split //, "rRseEfaqQtTdwWczxvgkoiOjpuPhynbml";
my @kor_key = split //, "ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎㅏㅐㅑㅒㅓㅔㅕㅖㅗㅛㅜㅠㅡㅣ";
#my @cho_data = split //, "ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ";
#my @jung_data = split //, "ㅏㅐㅑㅒㅓㅔㅕㅖㅗㅘㅙㅚㅛㅜㅝㅞㅟㅠㅡㅢㅣ";
#my @jong_data = split //, "ㄱㄲㄳㄴㄵㄶㄷㄹㄺㄻㄼㄽㄾㄿㅀㅁㅂㅄㅅㅆㅇㅈㅊㅋㅌㅍㅎ";

my %alp_num = (
    r =>  0, R =>  1, s =>  2, e =>  3, E =>  4, f =>  5,
    a =>  6, q =>  7, Q =>  8, t =>  9, T => 10, d => 11,
    w => 12, W => 13, c => 14, z => 15, x => 16, v => 17,
    g => 18, k => 19, o => 20, i => 21, O => 22, j => 23,
    p => 24, u => 25, P => 26, h => 27, y => 28, n => 29,
    b => 30, m => 31, l => 32,
);

my %jung_num = (
    ㅏ =>  0, ㅐ =>  1, ㅑ =>  2, ㅒ =>  3, ㅓ =>  4,
    ㅔ =>  5, ㅕ =>  6, ㅖ =>  7, ㅗ =>  8, ㅘ =>  9,
    ㅙ => 10, ㅚ => 11, ㅛ => 12, ㅜ => 13, ㅝ => 14,
    ㅞ => 15, ㅟ => 16, ㅠ => 17, ㅡ => 18, ㅢ => 19,
    ㅣ => 20,
);

my %jong_num = (
    ㄱ =>  0, ㄲ =>  1, ㄳ =>  2, ㄴ =>  3, ㄵ =>  4,
    ㄶ =>  5, ㄷ =>  6, ㄹ =>  7, ㄺ =>  8, ㄻ =>  9,
    ㄼ => 10, ㄽ => 11, ㄾ => 12, ㄿ => 13, ㅀ => 14,
    ㅁ => 15, ㅂ => 16, ㅄ => 17, ㅅ => 18, ㅆ => 19,
    ㅇ => 20, ㅈ => 21, ㅊ => 22, ㅋ => 23, ㅌ => 24,
    ㅍ => 25, ㅎ => 26,
);

my %num_jung = reverse %jung_num;
my %num_jong = reverse %jong_num;

my %double_jaeum = (
    "0,9" => 2,
    "3,12" => 4,
    "3,18" => 5,
    "7,0" => 8,
    "7,6" => 9,
    "7,7" => 10,
    "7,9" => 11,
    "7,16" => 12,
    "7,17" => 13,
    "7,18" => 14,
    "16,9" => 17,
);

my %double_moeum = (
    "8,19" => 9,
    "8,20" => 10,
    "8,32" => 11,
    "13,23" => 14,
    "13,24" => 15,
    "13,32" => 16,
    "18,32" => 19,
);

my $ret;
my @ret;
my $src = join ' ', @ARGV;
my @src = split //, $src;

my $cho;
my $jung;
my $jong;



sub hangul{
    my @arr = @_;
    $_ //= -1 for (@arr);
    my $var = 0xac00 + 21*28*$arr[0] + 28*$arr[1] + $arr[2] + 1;
    push @ret, chr($var);
}

#sub jung_index{
#    my $ch_jung = shift;
#    my $index_temp;
#    for(my $i=0; $i<=$#jung_data; $i++){
#        if($ch_jung eq $jung_data[$i]){
#            $index_temp = $i;
#            last;
#        }
#    }
#    $index_temp;
#}
#
#sub jong_index{
#    my $ch_jong = shift;
#    my $index_temp;
#    for(my $i=0; $i<=$#jong_data; $i++){
#        if($ch_jong eq $jong_data[$i]){
#            $index_temp = $i;
#            last;
#        }
#    }
#    $index_temp;
#}

sub jaeum{
    my ($ch, $index) = @_;
    if(!defined $jung){
        if(!defined $jong){
            if(!defined $cho){
                $cho = $index;
            } else {
                push @ret, $kor_key[$cho];
                $cho = $index;
            }
        }
    } else {
        if(!defined $jong){
            if(!defined $cho){
                push @ret, $num_jung{$jung};
                undef $jung;
                $cho = $index;
            } else {
                $jong = $jung_num{$ch};
            }
        } else {
            if(defined $cho){
                if( my $var = $double_jaeum{"$jong,$index"} ){
                    $jong = $var;
                    hangul($cho, $jung, $jong);
                    undef $jung;
                    undef $jong;
                    undef $cho;
                } else {
                    hangul($cho, $jung, $jong);
                    undef $jung;
                    undef $jong;
                    $cho = $index;
                }
            }
        }
    }
}

sub moeum{
    my ($ch, $index) = @_;

    if(!defined $cho){
        push @ret, $ch;
    } else {
        if(!defined $jong){
            if(!defined $jung){
                $jung = $jung_num{$ch};
            } else {                                #fix heerrere
                if(my $var = $double_moeum{"$jung,$index"}){
                    #my %rev = reverse %double_moeum;
                    $jung = $var;
                } else {
                    hangul($cho, $jung, $jong);
                    undef $cho;
                    $jung = $index_temp;
                }
            }
        } else {
            my $cho_temp;
            my $jong_temp;
            my %rev = reverse $double_jaeum;
            if(my $var = $rev{$jong}){
                $var =~ /(\d)+,(\d)+/;
                $jong = $1;
                $cho_temp = $2;
                hangul($cho, $jung, $jong);
                undef $jong;
            } else {
                $jong_temp = $jong;
                undef $jong;
                hangul($cho, $jung, $jong);
            }

            for(my $i=0; $i<19; $i++){
                if($jong_num{$jong_temp} eq $kor_key[$i]){
                    $jong_temp = $i;
                    last;
                }
            }

            if(defined $cho_temp){
                $cho = $cho_temp;
            } else {
                $cho = $jong_temp;
            }
            $jung = $jung_num{$ch};
        }
    }
}




for my $ch_src(@src){           #Start point
    my $index = $alp_num{$ch_src};
    $ch_src = $kor_key[$index];

    if(!defined $index){
        hangul($cho, $jung, $jong);
        undef $cho;
        undef $jung;
        undef $jong;
        push @ret, $ch_src;
        next;
    }

    if($index < 19){
        jaeum($ch_src, $index);
    } else {
        moeum($ch_src, $index);
    }
}



if(defined $cho){
    if(defined $jung){
        hangul($cho, $jung, $jong);
    } else {
        push @ret, $kor_key[$cho];
    }
} else {
    if(defined $jung){
        push @ret, $jung_num{$jung};
    } else {
        push @ret, $jong_num{$jong} if(defined $jong);
    }
}

$ret = join '', @ret;
print $ret;
