#!/bin/perl
#use utf8;
#use strict;
#use warnings;
#use Data::Dumper;
#use feature qw/
#    say
#/;

open TARGET, '<', 'Makefile';
open EXE, '>', '/tmp/__FILENAME42069';

for (<TARGET>){
    chomp;
    if(/TARGET = (.*)/){
        print EXE $1;
        close TARGET;
        close EXE;
        exit;
    }
}

print EXE 'a.out' unless defined $1;
close TARGET;
close EXE;
