#!/bin/perl
#use utf8;
#use strict;
#use warnings;
#use Data::Dumper;
#use feature qw/
#    say
#/;

open TARGET, '<', 'Makefile';
open EXE, '>', '/tmp/__FILENAME42069';

for (<TARGET>){
    chomp;
    if(/TARGET = (.*)/){
        print EXE $1;
        last;
    } else {
        print EXE 'a.out';
    }
}

close TARGET;
