#!/usr/bin/perl

use warnings;
use strict;

my $arg = shift @ARGV;
$arg or die "ARRRG\n";

while (<>) {
	# take one input line at a time
	chomp;
	if (/$arg/) {
		print "Matched: |$`<$&>$'|\n"; # the special match vars
	} else {
		print "No match: |$_|\n";
	}
}
