#!/bin/perl
#use utf8;
#use strict;
#use warnings;
#use Data::Dumper;
#use integer;
#use feature qw/
#    say
#/;

my $dir = $ENV{HOME}."/note/quicknotes/";
#system("mkdir -p $dir");

while(<>){
    my $line;
    my $filename;

    if (/^!(.*)/){
        $filename = "important";
        $line = $1;
    }
    if (/^\((.*?)\)(.*)/){
        $filename = $1;
        $line = $2;
    }

    open FILE, ">>", $dir.$filename or die "Can't open $filename!"; 
    print FILE $line."\n";
    close FILE;
}

chdir $dir;
system("~/util/delempty");
