#!/bin/perl
#use utf8;
#use strict;
#use warnings;
#use Data::Dumper;
#use integer;
#use feature qw/
#    say
#/;

my $dir = $ENV{HOME}."/note/";
chdir $dir;
#system("mkdir -p $dir");

while(<>){
    my $line;
    my $filename;

    if (/^!(.*)/){
        $filename = "important";
        $line = $1;
    } elsif (/^\((.*?)\)(.*)/){
        $filename = $1;
        $line = $2;
    } else {
        $filename = "quicknote";
        $line = $_;
    }

    open FILE, ">>", $filename or die "Can't open $filename!"; 
    print FILE $line."\n";
    close FILE;
}

system("~/util/delempty");
