#!/bin/sh

file=$(find -L ~ -maxdepth 3 -type f | ~/util/dirsed | fzf-tmux -p 100% \
	--tiebreak=begin --bind change:first --border-label "TMUGS-OPEN");
[ -z $file ] && exit 0
dir=$(dirname $file)
file=$(basename $file)

[ -n $file ] && tmux neww -c ~/"$dir" "nvim $file"
