#!/bin/sh

file=$(find ~ -mindepth 1 -maxdepth 3 -type f | ~/util/dirsed |\
    fzf-tmux -p 80% --tiebreak=begin --bind change:first --border-label "TMUGS-VIM");
[ -z $file ] && exit 0
directorie=$(dirname $file)
file_vim=$(basename $file)
[ -n $file ] && tmux neww -c ~/$directorie "nvim $file_vim"
