#!/bin/bash

alias=$(cat ~/.tmux-alias | fzf-tmux -n 1 -delimiter='/'\
    -p 50% --border-label='Tmugs-Alias' | cut -d '/' -f 1 | tr -d ' ')

case $alias in
    ae)
        tmux neww -n "aliasrc" "nvim ~/.aliasrc"
        ;;
    be)
        tmux neww -n "bashrc" "nvim ~/.bashrc"
        ;;
    cal)
        tmux neww "cal -3; date; sleep 60"
        ;;
    ch)
        ~/util/tmugs-CH
        ;;
    cd)
        tmux run-shell -b "~/util/tmugs-cd-root || exit 0; exec bash"
        ;;
    he)
        tmux neww -n "Homepage" -c ~/".dotfiles_private/projects/homepage" "nvim html/homepage.html"
        ;;
    md)
        tmux run-shell -b "~/util/tmugs-man-desc || exit 0; exec bash"
        ;;
    no)
        tmux run-shell -b "~/util/note; ~/util/tmugs-note || exit 0; exec bash"
        ;;
    nf)
        tmux neww "neofetch | ~/util/slowcat -1.3; sleep 3"
        ;;
    le)
        tmux neww -n "localhost" -c ~/"localhost" "nvim ."
        ;;
    pse)
        tmux neww -n "PerlSnip" -c ~/".config/nvim/snippets" "nvim perl.lua"
        ;;
    tae)
        tmux neww -n "tmux-alias" -c ~/"util" "nvim tmugs-alias"
        ;;
    ttt)
        tmux neww -n "typing" -c ~/".dotfiles" "nvim training"
        ;;
    te)
        tmux neww -n "tmuxconf" "nvim ~/.tmux.conf"
        ;;
    ve)
        tmux neww -n "nvim_set" -c ~/".config/nvim" "nvim init.lua"
        ;;
    *)
        #echo no
        ;;
esac
