#!/bin/sh

book=$(column -t ~/common/pdf/booklist |
    fzf-tmux -p 80% --tiebreak=begin --bind change:first\
    --border-label "TMUGS-BOOK" | awk '{ print $2 }')
[ -z "$book" ] && exit 0

if [ "$book" == "RECENT" ]
then
	book=$(fzf-tmux -p 80% --tiebreak=begin --bind change:first\
		--border-label "RECENT" < ~/common/pdf/booklist_recent)
	[ -z "$book" ] && exit 0
fi
~/util/tmugs-recent "$book" "common/pdf/booklist_recent"
zathura ~/common/pdf/$book.pdf &
