#!/bin/sh

str=$((cat ~/util/manlist ; apropos -s 1,1p .) | fzf-tmux -p 100% -n 1 \
	--delimiter=' ' --bind change:first --border-label "TMUGS-MAN")

[ -z "$str" ] && exit 0

cmd=$(echo "$str" | cut -d ' ' -f 1)
sec=$(echo "$str" | cut -d ' ' -f 2 | tr -d '()')

asdf=$(cut -d ' ' -f 1 ~/util/manlist)
for var in $asdf
do
    if [ "$cmd" = "$var" ]
    then
        exec ~/util/tmugs-man-ex $cmd
    fi
done

tmux neww -n "man($cmd)" "man $sec $cmd"
