#!/usr/bin/perl

$file = "$ENV{HOME}/common/pdf/booklist_recent";
$book = $ENV{book};
$book .= "\n";
$seen{"$book"}++;
push @list, $book;

open $fh, "<", $file or die "open failed\n";
while (<$fh>) {
	push @list, $_ unless $_ eq $book;
}
close $fh;

open $fh, ">", $file or die "open failed\n";
print $fh $_ for @list;
close $fh;
