#!/bin/sh

alias=$(fzf-tmux -n 1 -p 80% --border-label='Tmugs-Alias' \
	< ~/.tmux-alias | awk '{ print $1 }')

case $alias in
	ae) tmux neww -n "aliasrc" "nvim ~/.aliasrc" ;;
	ba) tmux run -b "~/personal/ba/ba || exit 0" ;;
	be) tmux neww -n "bashrc" "nvim ~/.bashrc" ;;
	tae) tmux neww -n "tmux-alias" -c ~/"util" "nvim tmugs-alias" ;;
	te) tmux neww -n "tmuxconf" "nvim ~/.tmux.conf" ;;
	ve) tmux neww -n "nvim_set" -c ~/".config/nvim" "nvim init.lua" ;;

	dbg) tmux neww -n "nvim_debug" -c ~/"test" "nvim .debug.sh" ;;
	ma) tmux neww -n "nvim_make" -c ~/"test" "nvim .make.sh" ;;
	run) tmux neww -n "nvim_run" -c ~/"test" "nvim .run.sh" ;;
	*) ;;
esac
