#!/usr/bin/sh

menu=$(printf "add\ncopy\nedit\nremove\nreset" | fzf-tmux -p 80% \
	--tiebreak=begin --bind change:first --border-label "TMUGS-FE")

case $menu in
	add) 
		perl -e '@que=qw/category title url stamp/; my @ans;
			for(@que){print "Enter the $_\n> "; chomp($ans=<>); push @ans, $ans}
			push @ans, "0"; die "Enter the category/title/url!\n" unless $ans[0] and $ans[1] and $ans[2];
			y/ /_/ for @ans;
			$ans[3] = "." unless $ans[3]; $new=join ",", @ans;
			open $fh, ">>", "$ENV{HOME}/personal/firefox_list" or die "open failed\n";
			print $fh "$new\n";
			close $fh or die "close failed\n"'
		;;
	copy)
		url=$( column -t -s',' ~/personal/firefox_list |\
			fzf-tmux -p 80% -n 1,2 --with-nth=1,2,4 \
			--tiebreak=begin --bind change:first --border-label "COPY")
		[ -z "$url" ] && exit 0
		export url
		perl -e '$url = $ENV{url}; @url = @{[split " ", $url]}; @que=qw/category title url stamp/;
			for(@que){$idx = each @que; 
				print "Enter the $_ (original: $url[$idx])\n> "; 
				chomp($ans=<>); $ans =~ y/ /_/; push @ans, $ans}

			for($i=0; $i<4; $i++){$url[$i] = $ans[$i] if $ans[$i]}
			$url[4] = 0;
			$url = join ",", @url;

			open $fh, ">>", "$ENV{HOME}/personal/firefox_list" or die "open failed\n";
			print $fh "$url\n";
			close $fh or die "close failed\n"'
		;;
	edit)
		url=$( column -t -s',' ~/personal/firefox_list |\
			fzf-tmux -p 80% -n 1,2 --with-nth=1,2,4 \
			--tiebreak=begin --bind change:first --border-label "EDIT")
		[ -z "$url" ] && exit 0
		export url
		perl -e '$url = $ENV{url}; @url = @{[split " ", $url]}; @que=qw/category title url stamp/;
			for(@que){$idx = each @que; 
				print "Enter the $_ (original: $url[$idx])\n> "; 
				chomp($ans=<>); $ans =~ y/ /_/; push @ans, $ans}

			for($i=0; $i<4; $i++){$url[$i] = $ans[$i] if $ans[$i]}

			$url = join ",", @{[split " ", $url]};
			$url_new = join ",", @url;

			open $fh, "<", "$ENV{HOME}/personal/firefox_list" or die "open failed\n";
			while(<$fh>){chomp; if(/\Q$url\E/){push @list,$url_new} else{push @list,$_}}
			close $fh or die "close failed\n";
			open $fh, ">", "$ENV{HOME}/personal/firefox_list" or die "open failed\n";
			print $fh "$_\n" for @list;
			close $fh or die "close failed\n"'
		;;
	remove)
		url=$( column -t -s',' ~/personal/firefox_list |\
			fzf-tmux -p 80% -n 1,2 --with-nth=1,2,4 \
			--tiebreak=begin --bind change:first --border-label "REMOVE")
		[ -z "$url" ] && exit 0
		export url
		perl -e '$url = $ENV{url}; @url = split " ", $url; $url = join ",", @url;
			open $fh, "<", "$ENV{HOME}/personal/firefox_list" or die "open failed\n";
			my @list;
			while(<$fh>){chomp; next if /\Q$url\E/; 
				if ($url[4]) {
					/(.*,)([^,]+)$/; $num=$2; $num-- if $num;
					$_ = $1.$num;
				}
				push @list, $_
			}
			close $fh or die "close failed\n";
			open $fh, ">", "$ENV{HOME}/personal/firefox_list" or die "open failed\n";
			print $fh "$_\n" for @list;
			close $fh or die "close failed\n"'
		;;
	reset)
		perl -e 'open $fh, "<", "$ENV{HOME}/personal/firefox_list" or die "open failed\n";
			my @list; while(<$fh>){chomp; /(\d+)$/; s//0/ if $1; push @list, $_}
			close $fh or die "close failed\n";
			open $fh, ">", "$ENV{HOME}/personal/firefox_list" or die "open failed\n";
			print $fh "$_\n" for @list; close $fh or die "close failed\n"'
		;;
esac

~/personal/firefox_sort
