#!/bin/sh

dir=$(find -L ~ -mindepth 1 -maxdepth 3 -type d | ~/util/dirsed |
	sed '1itest\n\/' | fzf-tmux -p 100% --bind change:first\
	--border-label "TMUGS-CD")

[ -z "$dir" ] && exit 0
[ "$dir" = "/" ] && ~/util/tmugs-cd-root && exit 0
[ -n "$dir" ] && tmux neww -c ~/"$dir"
