#!/usr/bin/perl

use warnings;
use strict;
use feature qw/ say /;
use Data::Dumper;
use Switch;

my $mark = "__MARKASDFQWERJKL__";

sub mac_im {
	my $arg = @_ ? shift : "argc";
	my $str = ($arg eq "v") ? "void" : "int argc, char *argv[]";
	return "int main($str)\n{\n\t$mark;\n\nreturn 0;\n}\n";
}

sub mac_inc {
	my $cnt = 1;

	for (@_) {
		my $str;
		switch ($_) {
			case "io" { $str = "<stdio.h>" } 
			case "lib" { $str = "<stdlib.h>" } 
			case "str" { $str = "<string.h>" } 
			#case "def" { $str = "<stddef.h>" } 
			case "uni" { $str = "<unistd.h>" } 
			case "fcn" { $str = "<fcntl.h>" } 
			case "wc" { $str = "<wchar.h>" } 
			case "." { $str = "\"$mark.h\""; $cnt = 0 }
			else { $str = "\"$_.h\"" }
		}
		print "#include $str\n";
	}

	print "$mark\n" if $cnt;
}

sub mac_wh {
	my $arg = @_ ? shift : "__def__";
	my $str = ($arg eq "b") ? "\n\t$mark" : " {\n\t$mark\n}";
	return "while ($mark)$str\n";
}

sub mac_fo {
	my $arg = @_ ? shift : "__def__";
	my $str = ($arg eq "b") ? "\n\t$mark" : " {\n\t$mark\n}";
	return "for ($mark)$str\n";
}

sub mac_sw {
	my $arg = @_ ? shift : "d";

	my $str;
	my $num = /(\d+)/ ? $1 : 1;
	my $def = $arg =~ /d/;
	my $brk = !($arg =~ /b/);
	my $exp = $arg =~ /e/;

	for (my $i = 1; $i <= $num; $i++) {
		$str .= "case $mark:\n";
		$str .= "\t$mark;\n" if $exp;
		$str .= "break;\n" if $brk;
	}
	$str .= "default:\n" if $def;
	$str .= "\t$mark;\n" if $exp;

	return "switch ($mark) {\n$str}\n"
}

sub mac_tyst {
	my $arg = @_ ? shift : $mark;
	return "typedef struct $arg {\n\t$mark\n} $arg;\n"
}

sub getmacro {
	my $str = shift;

	switch ($str) {
		case "def" { return "#define $mark\n" }
		case "fo" { return mac_fo(@_) }
		case "im" { return mac_im(@_) }
		case "inc" { mac_inc(@_) }
		case "NELEM" { return "#define NELEM(X)\t((sizeof(X))/(sizeof(X[0])))\n$mark\n" }
		case "pf" { return "printf($mark);\n" }
		case "sw" { return mac_sw(@_) }
		case "tyst" { return mac_tyst(@_) }
		case "wh" { return mac_wh(@_) }
		else { print "$str@_\n" }
	}
}

while (<>) {
	my @arg;

	chomp;
	s/^\s+//;
	@arg = split ' ', $_;
	print getmacro(@arg);
}
print "__MARKPOSTTT__\n";
