#!/usr/bin/perl
#!/usr/bin/perl -d

#reinventing of 'column -t' but it also align wide characters

#use warnings;
#use strict;

use utf8;
use open qw(:std :utf8);
use Text::CharWidth;

my $s = shift // " ";
my @l;
my @lo;
my @m;
my $ma = 0;

sub max {
	my $m = shift;
	for (@_) {
		$m = $_ if $_>$m;
	}

	$m
}

while(<>) {chomp; push @l, $_}

for (@l) {
	my @o;
    my @c  =  split "$s",$_;
	$ma = max $ma, scalar @c;
    for (@c) {
        my $i = each @c;
		$m[$i] ||= 0;
		my $len = Text::CharWidth::mbswidth($_);
		push @o, ($len - length);
        $m[$i] = max $m[$i], $len;
    }
	push @lo, \@o;
}

for (@l) {
	my $f = "";
	my $i = each @l;
	my @c = split "$s",$_;

	for (@c) {
		my $j = each @c;
		my $spc = $m[$j] - $lo[$i][$j];
		$m[$j] ||= 1;
		$_ ||= '.';
		$f .= "%-${spc}s ";
	}
	$f .= "\n";
	printf $f, @c
}
