#!/bin/perl
use utf8;
use strict;
use warnings;
use diagnostics;
use feature qw/
    say
/;

#Simple Comment Toggle for Bash
while(my $line = <>){
    if ($line =~ /^(\s*)#/){
        $line =~ s//$1/m;
    } else {
        $line =~ s/^(\s*)/#$1/m;
    }
    say STDOUT $line;
}
